version: "2"

services:
  pihole:
    container_name: pihole
    image: ubpihole:latest
    hostname: pihole
    domainname: pihole.local
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      ADMIN_EMAIL: "someone@somewhere.com"
      TZ: "America/Los_Angeles"
      WEBPASSWORD: "your_password"
      DNS1: 127.0.0.1#5335
      DNS2: 127.0.0.1#5335
      DNSSEC: "false" # Leave this one - config is in unbound
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole-unbound_dnsmasq:/etc/dnsmasq.d:rw
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
volumes:
  etc_pihole-unbound:
    driver: local 
  etc_pihole-unbound_dnsmasq:
    driver: local 